# helm install gossipqa-prom prometheus-community/prometheus -f automation/terraform/testnets/gossipqa/values.yaml

## Define serviceAccount names for components. Defaults to component's fully qualified name.
##
serviceAccounts:
  nodeExporter:
    create: false
    name:
    annotations: {}

server:

  ## namespaces to monitor (instead of monitoring all - clusterwide). Needed if you want to run without Cluster-admin privileges.
  namespaces:
    - gossipqa