# helm install gossipqa-prom prometheus-community/prometheus -f automation/terraform/testnets/gossipqa/values.yaml

nodeExporter:
  ## If false, node-exporter will not be installed
  ##
  enabled: false

alertmanager:
  ## If false, alertmanager will not be installed
  ##
  enabled: false

server:

  ## namespaces to monitor (instead of monitoring all - clusterwide). Needed if you want to run without Cluster-admin privileges.
  namespaces:
    - gossipqa